version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - store_artifacts:
          path: main.py  # Uložíme hlavní soubor jako artefakt (pokud je to potřeba)

  deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Deploy
          command: ./deploy.sh  # Skript pro nasazení

workflows:
  version: 2
  example:
    jobs:
      - build
      - deploy:
          requires:
            - build
